docker run -i -e CLIENT_QOS=1 -e CLIENT_TOPIC=asd -e CLIENT_SUBSCRIBERS=2 -e CLIENT_SUBSCRIBERS_COUNT=10 -e CLIENT_HOSTNAME="172.17.0.2" clients &
docker run -i -e CLIENT_QOS=1 -e CLIENT_TOPIC=asd -e CLIENT_SUBSCRIBERS=2 -e CLIENT_SUBSCRIBERS_COUNT=10 -e CLIENT_HOSTNAME="172.17.0.3" clients &
docker run -i -e CLIENT_QOS=1 -e CLIENT_TOPIC=asd -e CLIENT_SUBSCRIBERS=2 -e CLIENT_SUBSCRIBERS_COUNT=10 -e CLIENT_HOSTNAME="172.17.0.4" clients &
docker run -i -e CLIENT_QOS=1 -e CLIENT_TOPIC=asd -e CLIENT_SUBSCRIBERS=2 -e CLIENT_SUBSCRIBERS_COUNT=10 -e CLIENT_HOSTNAME="172.17.0.5" clients &
docker run -i -e CLIENT_QOS=1 -e CLIENT_TOPIC=asd -e CLIENT_SUBSCRIBERS=2 -e CLIENT_SUBSCRIBERS_COUNT=10 -e CLIENT_HOSTNAME="172.17.0.6" clients &